#!/bin/bash
diff -s zrun1 zrun2 | less
diff -s zrun1 zrun3 | less
diff -s zrun1 zrun4 | less
diff -s zrun1 zrun5 | less
diff -s zrun1 zrun6 | less
diff -s zrun1 zrun7 | less
diff -s zrun1 zrun8 | less
diff -s zrun1 zrun9 | less
diff -s zrun2 zrun3 | less
diff -s zrun2 zrun4 | less
diff -s zrun2 zrun5 | less
diff -s zrun2 zrun6 | less
diff -s zrun2 zrun7 | less
diff -s zrun2 zrun8 | less
diff -s zrun2 zrun9 | less
diff -s zrun3 zrun4 | less
diff -s zrun3 zrun5 | less
diff -s zrun3 zrun6 | less
diff -s zrun3 zrun7 | less
diff -s zrun3 zrun8 | less
diff -s zrun3 zrun9 | less
diff -s zrun4 zrun5 | less
diff -s zrun4 zrun6 | less
diff -s zrun4 zrun7 | less
diff -s zrun4 zrun8 | less
diff -s zrun4 zrun9 | less
diff -s zrun5 zrun6 | less
diff -s zrun5 zrun7 | less
diff -s zrun5 zrun8 | less
diff -s zrun5 zrun9 | less
diff -s zrun6 zrun7 | less
diff -s zrun6 zrun8 | less
diff -s zrun6 zrun9 | less
diff -s zrun7 zrun8 | less
diff -s zrun7 zrun9 | less
diff -s zrun8 zrun9 | less

